#define EFJSON_STREAM_IMPL
#define EFJSON_CONF_UTF_ENCODER 0
#define EFJSON_CONF_UNICODE 1
#define EFJSON_CONF_FIXED_STACK 0
#define EFJSON_CONF_PRETTIER_TYPE 0
#define EFJSON_CONF_PRETTIER_CATEGORY 0
#define EFJSON_CONF_PRETTIER_ERROR 1
#define EFJSON_CONF_PRETTIER_LOCATION 0
#define EFJSON_CONF_EXPOSE_UNICODE 0
#define EFJSON_CONF_CHECK_POSITION_OVERFLOW 0
#define EFJSON_CONF_COMBINE_ESCAPED_SURROGATE 1
#define EFJSON_CONF_CHECK_INPUT_UTF 0
#define EFJSON_CONF_CHECK_ESCAPE_UTF 1
#include "efjson_stream.h"
